# URL com o prefixo jdbc:
spring.datasource.url=jdbc:postgresql://ep-twilight-dew-amnhl6dx-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require

# Credenciais (que eu peguei da sua string)
spring.datasource.username=neondb_owner
spring.datasource.password=npg_h7cOsktgVGo2

# Driver e Dialeto (importante para o Hibernate não se perder)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Opcional: Cria as tabelas automaticamente se não existirem
spring.jpa.hibernate.ddl-auto=update