# Configuração para PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-twilight-dew-amnhl6dx-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
# Senha atualizada conforme você enviou
spring.datasource.password=npg_STKgs5AM3uZL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mostra o SQL no console (bom para debugar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Garante que o Hibernate não tente validar o banco antes da hora
spring.jpa.generate-ddl=true